AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance.

Resources:
  MoazzamEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0928f4202481dfdf6
      InstanceType: t2.micro
      KeyName: moazzam-oregon
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0


