AWSTemplateFormatVersion: 2010-09-09
Description: Parameter Intro

Parameters:
  MyKeyName:
    Description: Parametrizing the key name 
    Type: AWS::EC2::KeyPair::KeyName
  MyAZ:
    Description: Parametrizing the  Availabilty Zone
    Type: String
    Default: us-west-2a
    AllowedValues:
      - us-west-2a
      - us-west-2b
      - us-west-2c
  MyEC2Type:
    Description: Parametrizing the  Instance type from SSM
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.small
      - t2.micro

Resources:
  MoazzamEC2Instance:
    Type: AWS::EC2::Instance
    Properties:

      ImageId: ami-0928f4202481dfdf6
      InstanceType: !Ref MyEC2Type
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
      AvailabilityZone: !Ref MyAZ
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
  EIPforEC2:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref MoazzamEC2Instance