AWSTemplateFormatVersion: 2010-09-09
Description: Nested Stack testing

Parameters:

  MoazzamVPCID:
    Description: "Importing VPC ID"
    Type: String



Resources:
  SSHSecurity: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH  Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
      VpcId: !Ref MoazzamVPCID

Outputs:
  MySGID:
    Description: Output my Public Subnet ID
    Value: !Ref SSHSecurity